# Generated by Django 2.1 on 2018-08-12 18:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('country', models.CharField(default='Iran', max_length=25)),
                ('city', models.CharField(default='Tehran', max_length=50)),
                ('district', models.IntegerField()),
                ('number_of_people_in_the_household', models.IntegerField()),
                ('number_of_rooms', models.IntegerField()),
                ('joined_on', models.DateField()),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
