# Generated by Django 2.1 on 2018-08-15 04:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        ('collected_data', '0003_auto_20180814_0936'),
    ]

    operations = [
        migrations.CreateModel(
            name='Norm',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.DecimalField(decimal_places=2, max_digits=15)),
                ('start_hour', models.TimeField(unique=True)),
                ('end_hour', models.TimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Notif',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('for_data', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='collected_data.EData')),
                ('for_user', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='accounts.Profile')),
            ],
        ),
    ]
