# Generated by Django 2.1 on 2018-08-12 19:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userId', models.CharField(max_length=100)),
                ('value', models.DecimalField(decimal_places=10, max_digits=15)),
                ('date', models.DateField()),
                ('time', models.TimeField()),
            ],
        ),
    ]
