# Generated by Django 2.1 on 2018-08-12 19:20

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collected_data', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='edata',
            name='time',
        ),
        migrations.AlterField(
            model_name='edata',
            name='date',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
    ]
